# Generated by Django 3.2.4 on 2021-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('blood_group', models.CharField(max_length=3)),
                ('date_last_donated', models.DateField(default=30, max_length=12, null=True)),
                ('town', models.CharField(default=30, max_length=10, null=True)),
                ('county', models.CharField(default=30, max_length=12, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('phonenumber', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
