# Generated by Django 3.2.9 on 2021-11-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='image',
        ),
    ]
