# Generated by Django 3.2.8 on 2021-10-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=3)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('Date_last_donated', models.DateField()),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
