# Generated by Django 3.2.8 on 2021-10-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_auto_20211026_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeals',
            old_name='date_last_donated',
            new_name='date_of_appeal',
        ),
    ]
