# Generated by Django 3.2.4 on 2021-10-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('age', models.PositiveSmallIntegerField(default=None)),
                ('hospital', models.CharField(default=None, max_length=50)),
                ('ward', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('blood_pints', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
